### ISSUE TITLE
action language on call congress page

### ISSUE THREAD

**Issue by seemala** [18mr/keepushome#1]
![screen shot 2015-04-09 at 12 44 03 pm](https://cloud.githubusercontent.com/assets/8630999/7075367/32f6344a-deb6-11e4-8fff-ffe6a5ef3bd8.png)

change "Signatures Collected" to "Calls Made"
change "SIGN THIS PETITION" to "TAKE ACTION"? "JOIN US"?

these may be limitations of actionnetwork. if so, ignore this :)

**Comment by catachresis** [comment]
Good catch. Totally didn't think about this. "SIGN THIS PETITION" is an easy fix; just pushed some code. To fix the "Signatures Collected" I'm going to have to write a little more, since it'll involve a request to ActionNetwork's API. It'll be a useful snippet, but I'm going to have to backburner it for now.

**Comment by seemala** [comment]
At the end of the day, not super urgent re: "signatures collected"

**Comment by seemala** [comment]
Oops. Meant to just comment. Backburner works. Not the most urgent piece of the campaign at this point.

**Comment by seemala** [comment]
Nice! Looks great! And already up to our 42 calls!

C. M. Samala   /   c.samala@gmail.com
Google Voice   /  707 SAMALA C
Twitter  /  samala http://twitter.com/samala
